# Generated by Django 4.2.4 on 2023-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=500)),
                ('predict', models.CharField(max_length=50)),
            ],
        ),
    ]
